comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
